baseURL: https://claucia.com/
languageCode: en-us
title: Cláucia Cambruzzi
theme: nica
copyright: 2022 © Cláucia Cambruzzi

params:
  author: Cláucia Cambruzzi
  description: I am learning web development and this is my humble website.
  social:
    - identifier: github
      url: https://github.com/claucia
      pre: <i class="lni lni-github-original"></i>
    - identifier: linkedin
      url: https://www.linkedin.com/in/claucia/
      pre: <i class="lni lni-linkedin-original"></i>
  contact:
    form:
      url: https://script.google.com/macros/s/AKfycbyRpvybj9Gk3z11LTivHknJoK3SkEXIO-a0bC7vZL26ZkHsqpb0bMlSNPQXQsVC_7U7Ag/exec

menu:
  main:
    - identifier: portfolio
      name: Portfolio
      title: Portfolio
      url: /portfolio/
      weight: 10
    - identifier: cv
      name: CV
      title: CV
      url: /cv/
      weight: 20
    - identifier: about
      name: About
      title: About
      url: /about/
      weight: 30
    - identifier: contact
      name: Contact
      title: Contact
      url: /contact/
      weight: 40

taxonomies:
  tag: tags

googleAnalytics: G-74XNJ2B5W6

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:    
    noClasses: false # This requires a stylesheet for syntax highlighting
                     # This can be used to generate one:
                     # hugo gen chromastyles --style=monokai > syntax.css
                     # Available styles: https://xyproto.github.io/splash/docs/
                     # These also seem to work just fine: https://swapoff.org/chroma/playground/
